title: Mitchell's Blog
description: >
url: "https://mitchallain.github.io"
paginate:	2 # The number of posts to show per page on your homepage
name: "Mitchell Allain"
email: "allain.mitch@gmail.com"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
  - jemoji
google_analytics: G-N9G5289DKX
